package com.mall.mapper;

import com.mall.dto.ResourceInfo;
import com.mall.dto.ResourceInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author lb
 */
@Mapper
public interface ResourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int countByExample(ResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByExample(ResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insert(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insertSelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    List<ResourceInfo> selectByExample(ResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    ResourceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") ResourceInfo record, @Param("example") ResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExample(@Param("record") ResourceInfo record, @Param("example") ResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKeySelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKey(ResourceInfo record);

    /**
     * 批量插入
     * @param record
     * @return
     */
    void batchInsert(List<ResourceInfo> record);
}