package com.mall.mapper;

import com.mall.dto.RoleMenuInfo;
import com.mall.dto.RoleMenuInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author lb
 */
@Mapper
public interface RoleMenuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int countByExample(RoleMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByExample(RoleMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insert(RoleMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insertSelective(RoleMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    List<RoleMenuInfo> selectByExample(RoleMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    RoleMenuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") RoleMenuInfo record, @Param("example") RoleMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExample(@Param("record") RoleMenuInfo record, @Param("example") RoleMenuInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKeySelective(RoleMenuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKey(RoleMenuInfo record);
}