package com.mall.mapper;

import com.mall.dto.RoleResourceInfo;
import com.mall.dto.RoleResourceInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author lb
 */
@Mapper
public interface RoleResourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int countByExample(RoleResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByExample(RoleResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insert(RoleResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insertSelective(RoleResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    List<RoleResourceInfo> selectByExample(RoleResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    RoleResourceInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") RoleResourceInfo record, @Param("example") RoleResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExample(@Param("record") RoleResourceInfo record, @Param("example") RoleResourceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKeySelective(RoleResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKey(RoleResourceInfo record);
}