package com.mall.mapper;

import com.mall.dto.UserRoleInfo;
import com.mall.dto.UserRoleInfoExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @author lb
 */
@Mapper
public interface UserRoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int countByExample(UserRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByExample(UserRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insert(UserRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int insertSelective(UserRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    List<UserRoleInfo> selectByExample(UserRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    UserRoleInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") UserRoleInfo record, @Param("example") UserRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByExample(@Param("record") UserRoleInfo record, @Param("example") UserRoleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKeySelective(UserRoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    int updateByPrimaryKey(UserRoleInfo record);
}