package com.mall.dto;

import java.io.Serializable;
import java.util.Date;

public class ResourceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.name
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.url
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.description
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.create_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource_info.modify_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.id
     *
     * @return the value of resource_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.id
     *
     * @param id the value for resource_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.name
     *
     * @return the value of resource_info.name
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.name
     *
     * @param name the value for resource_info.name
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.url
     *
     * @return the value of resource_info.url
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.url
     *
     * @param url the value for resource_info.url
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.description
     *
     * @return the value of resource_info.description
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.description
     *
     * @param description the value for resource_info.description
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.create_time
     *
     * @return the value of resource_info.create_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.create_time
     *
     * @param createTime the value for resource_info.create_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource_info.modify_time
     *
     * @return the value of resource_info.modify_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource_info.modify_time
     *
     * @param modifyTime the value for resource_info.modify_time
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", url=").append(url);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}