package com.mall.dto;

import java.io.Serializable;

public class RoleMenuInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_info.role_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu_info.memu_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private Long memuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_info.id
     *
     * @return the value of role_menu_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_info.id
     *
     * @param id the value for role_menu_info.id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_info.role_id
     *
     * @return the value of role_menu_info.role_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_info.role_id
     *
     * @param roleId the value for role_menu_info.role_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu_info.memu_id
     *
     * @return the value of role_menu_info.memu_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public Long getMemuId() {
        return memuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu_info.memu_id
     *
     * @param memuId the value for role_menu_info.memu_id
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    public void setMemuId(Long memuId) {
        this.memuId = memuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu_info
     *
     * @mbggenerated Wed Mar 02 14:56:31 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", memuId=").append(memuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}